# on Alpha:
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
enable_cpu_affinity: false
gpu_ids: 0,1
machine_rank: 0
main_process_ip: 192.168.1.150
main_process_port: 29501
main_training_function: main
mixed_precision: 'no'
num_machines: 2
# num_processes = num_on_alpha + num_on_beta
num_processes: 4
rdzv_backend: static
same_network: false
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

# On Beta:
# compute_environment: LOCAL_MACHINE
# distributed_type: MULTI_GPU
# downcast_bf16: 'no'
# gpu_ids: 6,7
# machine_rank: 1
# main_process_ip: 192.168.1.150
# main_process_port: 29501
# main_training_function: main
# mixed_precision: 'no'
# num_machines: 2
# # num_processes = num_on_alpha + num_on_beta
# num_processes: 2
# rdzv_backend: static
# same_network: false
# tpu_env: []
# tpu_use_cluster: false
# tpu_use_sudo: false
# use_cpu: false
